title: College financial calculator
description: Calculator that helps plan how much needs to be invested now, using a variety of investment strategies, in order to pay for college in the future.
blog_post: https://daveeargle.com/2018/08/09/College-Financial-Calculator/

lang: en-US
theme: jekyll-theme-primer

google_analytics: 'UA-35065822-1'

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
